########### 自定义配置 ：尽量以驼峰命名方式：因为@Value注解不支持中划线转驼峰，@ConfigurationProperties倒是支持 宽松绑定 ######################
my:
  file:
    pic:
      picRootPath: "/opt/mynginx/images/"          # 指向的必须是nginx配置的存放静态资源的根目录

spring:
  cloud:
    nacos:
      discovery: # 配置nacos注册中心服务发现
        group: "test_group"