spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://101.34.5.36:8848
        namespace: "e41ecd75-7155-4e7b-a78e-904c3739fb38"
  datasource:
    url: "jdbc:mysql://106.15.235.113:3306/scrm?useUnicode=true&characterEncoding=utf8&&useSSL=false&serverTimezone=GMT%2B8"
    username: root
    password: "!MySQL123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

my:
  file:
    pic:
      picRootPath: "/opt/mynginx/images/"
      picAccessPath: "https://www.fzk-tx.top/images"