server:
  port: 30001

spring:
  application:
    name: manage
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB  # 上传文件最大限制

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    # 配置日志  选择了默认的控制台输出  如果选择log4j或slf4j，需要导入包
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

my:
  file:
    pic:
      toCompressSize: 1024000                            # 图片大小达到此值，将进行0.5压缩，单位byte
      format: "jpeg,jpg,png,gif,svg,bmp,ico,tiff"            # 图片格式
      type: "articleImage,userIcon,productImage,customerIcon"        # 图片类型

  jwt:
    secret: "scrm"
    timeout: 604800 # Token有效期，一周，单位：s
    loginIdKey: userID
  # 用友
  iuap:
    appid: "20b486cefc83889f"
    secret: "4b8f340cb3b127950bfb4c632d355c5ab5330bb1bd7b4e7307ccf68217e5"
