spring:
  cloud:
    nacos:
      discovery: # 配置nacos注册中心服务发现
        server-addr: http://localhost:8848 # 配置的Nacos地址
        namespace: "e41ecd75-7155-4e7b-a78e-904c3739fb38" # 这是scrm的名称空间，可以去nacos地址看看
  datasource:
    url: jdbc:mysql://localhost:3306/scrm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "!MySQL123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: "!MyRedis1233211234567"

nginx:
  file:
    pic:
      root-path: "/usr/local/nginx/data/"
      access-path: "http://118.122.48.47:33333/data"