spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://101.34.5.36:8848
        namespace: "e41ecd75-7155-4e7b-a78e-904c3739fb38"
  datasource:
    url: jdbc:mysql://106.15.235.113:3306/scrm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "!MySQL123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.15.235.113
    port: 6379
    password: "!MyRedis1233211234567"

nginx:
  file:
    pic:
      root-path: "E:/Nginx/nginx-1.20.2/data/"
      access-path: "http://localhost"