#微服务建议一定要写服务端口号和微服务名称
server:
  port: 30001

spring:
  application:
    # 微服务名称
    name: gateway
  cloud:
    nacos:
      discovery: # 配置nacos注册中心服务发现
        server-addr: http://101.34.5.36:8848  #配置的Nacos地址
        namespace: "e41ecd75-7155-4e7b-a78e-904c3739fb38" # 这是scrm的名称空间，可以去nacos地址看看
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由(默认false)
      routes:
        - id: service # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://service
          predicates:
            - Path=/se/** # 断言，路径相匹配的进行路由
#          filters:
#            - StripPrefix=1
        - id: marketing # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://marketing
          predicates:
            - Path=/mk/** # 断言，路径相匹配的进行路由
#          filters:
#            - StripPrefix=1
      loadbalancer:
        use404: true  # 当无法找到服务实例时，返回404，默认返回503
  # gateway是基于WebFlux开发的，不能引入springmvc，或者这里配置web环境为reactive
  main:
    web-application-type: reactive
