#微服务建议一定要写服务端口号和微服务名称
server:
  port: 30003
spring:
  application:
    # 微服务名称
    name: marketing
  cloud:
    nacos:
      discovery: # 配置nacos注册中心服务发现
        server-addr: http://101.34.5.36:8848  #配置的Nacos地址
        namespace: "e41ecd75-7155-4e7b-a78e-904c3739fb38" # 这是scrm的名称空间，可以去nacos地址看看

  datasource:
    url: "jdbc:mysql://localhost:3306/scrm?useUnicode=true&characterEncoding=utf8&&useSSL=false&serverTimezone=GMT%2B8"
    username: root
    password: "!MySQL123456"
    driver-class-name: com.mysql.cj.jdbc.Driver