#微服务建议一定要写服务端口号和微服务名称
server:
  port: 30003

spring:
  application:
    # 微服务名称
    name: marketing
  cloud:
    nacos:
      discovery: # 配置nacos注册中心服务发现
        server-addr: http://101.34.5.36:8848  #配置的Nacos地址
        namespace: "e41ecd75-7155-4e7b-a78e-904c3739fb38" # 这是scrm的名称空间，可以去nacos地址看看
  datasource:
    url: "jdbc:mysql://106.15.235.113:3306/scrm?useUnicode=true&characterEncoding=utf8&&useSSL=false&serverTimezone=GMT%2B8"
    username: root
    password: "!MySQL123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置日志  选择了默认的控制台输出   如果选择log4j或slf4j，需要导入包
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名